"""empty message

Revision ID: 344019d6139a
Revises: 
Create Date: 2023-02-16 17:56:05.786218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344019d6139a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=80), nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('edad', sa.String(length=80), nullable=True),
    sa.Column('tamaño', sa.String(length=80), nullable=True),
    sa.Column('genero', sa.String(length=80), nullable=True),
    sa.Column('raza', sa.String(length=80), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('contacto', sa.String(length=80), nullable=False),
    sa.Column('ubicacion', sa.String(length=80), nullable=False),
    sa.Column('foto1', sa.String(length=250), nullable=False),
    sa.Column('foto2', sa.String(length=80), nullable=True),
    sa.Column('foto3', sa.String(length=80), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascota')
    op.drop_table('usuario')
    # ### end Alembic commands ###
