"""empty message

Revision ID: ce0bd582e2da
Revises: 1bc7ab97cc64
Create Date: 2023-02-03 20:18:03.166440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0bd582e2da'
down_revision = '1bc7ab97cc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mascota', 'edad',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.add_column('usuario', sa.Column('celular', sa.String(length=15), nullable=True))
    op.alter_column('usuario', 'direccion',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'direccion',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('usuario', 'celular')
    op.alter_column('mascota', 'edad',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
